using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Customer : MonoBehaviour
{
    // SHOULD HAVE:
    // - Name
    // - List of traits
    // - Stats
    // A customer will be randomly generated by another script, which means that the variables below may be added to another script called CustomerData
    
    [SerializeField] SpriteRenderer spriteRenderer;
    [SerializeField] SurvivalKit _survivalKit;

    // Maybe CustomerData should be a mono
    private CustomerData _data;
    private float _survivabilityScore; // Will be a percentage in game

    // private string _name;
    
    // Customer's counting stats
    // POSSIBLE IMPROVEMENT: Make a CustomerStat class and make child classes that represent stats below
    // [Range(1,5)]
    // [SerializeField] int _strength;
    // [Range(1,5)]
    // [SerializeField] int _vitality;
    // [Range(1,5)]
    // [SerializeField] int _perception;
    // [Range(1,5)]
    // [SerializeField] int _intelligence;

    // Start is called before the first frame update
    void Start()
    {
        spriteRenderer = GetComponentInChildren<SpriteRenderer>();
        _survivalKit = GetComponent<SurvivalKit>();
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void AffectSurvivabilityScore(float effect)
    {
        // Change survivabilityScore logic here
        _survivabilityScore += effect;
        
        // Make sure survivability score will stay in between 0-100%
        if(_survivabilityScore > 1){
            _survivabilityScore = 1;
        }else if(_survivabilityScore < 0){
            _survivabilityScore = 0;
        }
    }

    public void SetData(CustomerData data)
    {
        _data = data;
        Debug.Log(_data);
    }

    public SurvivalKit GetSurvivalKit()
    {
        return _survivalKit;
    }

    public CustomerData GetCustomerData()
    {
        return _data;
    }


}
